author:
  name: "Moritz Seebacher"
  avatar: "/Seebacher-Moritz_2023_7_ret_pass_format.jpg"
  bio: "PhD student at the ifo Institute and LMU Munich."
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:seebacher@ifo.de"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/moritz-seebacher-853974223/"

title: "Moritz Seebacher"
description: "Research • Education & Labor Economics"
url: "https://moseeb98.github.io"
baseurl: ""
timezone: Europe/Berlin
locale: en

# Minimal Mistakes via remote theme
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown & permalinks
markdown: kramdown
kramdown:
  input: GFM
permalink: /:title/

# (Optional) pick a skin: default, air, contrast, dark, neon, sunrise, etc.
minimal_mistakes_skin: "default"
